[project]
name = "unit-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Giorgio Azzinnaro", email = "giorgio@azzinna.ro" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
unit-text = "unit_text:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
