[project]
name = "unit-text-core"
version = "0.1.0"
description = "Core library for unit-text"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["ollama", "llm", "language", "unit", "test"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
authors = [
    { name = "Giorgio Azzinnaro", email = "giorgio.azzinnaro@sealambda.com" },
    { name = "Sealambda", email = "hello@sealambda.com" },
]
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.7",
    "pydantic>=2.10.6",
    "dicttoxml>=1.7.16",
]

[project.urls]
source = "https://github.com/sealambda/unit-text"
issues = "https://github.com/sealambda/unit-text/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/unit_text_core"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
]